package-lock.json

Configurações Iniciais do projeto

[Grupo 30] - Configurações Iniciais

---

package-lock.json
package.json
src/index.js
src/redux/reducers/index.js
src/redux/reducers/user.js
src/redux/store/index.js

Criando arquivos iniciais do redux

[Grupo 25] config redux

---

package-lock.json
src/App.js
src/hooks/useLoginForm.js
src/pages/Login.js

[Grupo 26] Tela de login

---

package-lock.json
src/App.js
src/Components/Drinks.js
src/Components/Explorer.js
src/Components/FavoriteRecipes.js
src/Components/Foods.js
src/Components/Login.js
src/Components/Perfil.js
src/Components/Recipes.js
src/context/GlobalContext.js
src/context/Provider.js
src/index.js
src/routes/index.js

[GRUPO 13] App Receitas - Iniciando o projeto

[GRUPO 13] App Receitas - Iniciando o projeto

---

src/Pages/Login.jsx

[Group-39] - [Componente de Login, Validação de Email e Senha]

---

src/App.js
src/pages/Login.js
src/provider/index.js
src/routes/index.js

[Group 19] - Rollback

---

package-lock.json
src/components/DataUserLogin.js
src/pages/Login.js

Finalizados os 7 requisitos do tela de login.
Requisitos 2 -> 8

[Group 25 ] Login screen

---

src/App.js
src/Routes.js
src/pages/Login.js

[Grupo 30] -  Tela de Login

---

src/App.js
src/pages/ExplorarBebidas.jsx
src/pages/ExplorarComidas.jsx
src/pages/Login.jsx
src/tests/login.test.js

Faz alterações no handleLogin e senha

Group-12 - Ajusta inputs de login e senha

---

src/App.js
src/Context/UserHook.js
src/components/Clipboard.js
src/services/RequestDrinks.js
src/services/RequestFood.js

adiciona botão de compartilhar tela

[Melhor que lasanha] Main group 31 page login

---

src/App.js
src/components/Header.js
src/pages/DoneRecipes.js
src/pages/Explorer.js
src/pages/FavoriteRecipes.js
src/pages/Profile.js
src/pages/drinks/DrinkExplorer.js
src/pages/drinks/DrinkExplorerByIngredients.js
src/pages/drinks/DrinkInProgress.js
src/pages/drinks/DrinkRecipes.js
src/pages/drinks/Drinks.js
src/pages/foods/FoodExplorer.js
src/pages/foods/FoodExplorerByCountry.js
src/pages/foods/FoodExplorerByIngredients.js
src/pages/foods/FoodInProgress.js
src/pages/foods/FoodRecipes.js
src/pages/foods/Foods.js

Corrigidas rotas que estavam com espaço extra
Adicionei Header em todas páginas que exigiam
Adicionei props ao Header para que título e botão search sejam adicionados dinamicamente

[Grupo 29] Requisito 11

---

src/Routes.js
src/components/Header.js
src/pages/Drinks.js
src/pages/ExplorerMealsIngredients.js
src/pages/ExplorerMealsOrigin.js
src/pages/Meals.js
src/pages/Profile.js
src/pages/RecipesDone.js
src/pages/RecipesFavorites.js

Faltando implementar requisito 16

[Grupo 30] - Mergeando Projeto

---

src/App.js
src/components/Footer.js
src/pages/Drink.js
src/pages/Explore.js
src/pages/ExploreDrinks.js
src/pages/ExploreDrinksIngredientes.js
src/pages/ExploreFoods.js
src/pages/ExploreFoodsArea.js
src/pages/ExploreFoodsIngredientes.js
src/pages/FavoritedRevenues.js
src/pages/Foods.js
src/pages/Login.js
src/pages/MakedRevenues.js
src/pages/Perfil.js

Requisitos com o uso do footer concluidos.
Requisitos 19 -> 24

[Group 25] Lower menu

---

src/App.js
src/pages/ExplorarBebidas.jsx
src/pages/ExplorarBebidasIngredientes.jsx
src/pages/ExplorarComidasArea.jsx
src/pages/ExplorarComidasIngredientes.jsx
src/pages/Perfil.js
src/pages/ReceitasFavoritas.jsx
src/pages/ReceitasFeitas.jsx

Main group 34 req10

---

src/App.js
src/components/DrinkCard.js
src/components/FoodCard.js
src/components/Header.js
src/components/SearchBar.js
src/pages/Drinks.js
src/pages/Foods.js
src/redux/actions/index.js
src/redux/reducers/drinkReducer.js
src/redux/reducers/foodReducer.js
src/redux/reducers/index.js

[Grupo 25] Searchbar requisitos 13 a 18

---

public/index.html
src/App.js
src/components/Header.js
src/components/RenderCategories.js
src/components/RenderCategoriesDrinks.js
src/components/RenderCategoriesMeals.js
src/pages/HomeDrinks.js
src/pages/HomeRecipe.js
src/pages/Login.js
src/redux/actions/index.js

[GROUP 3] - Recipes Main Screen

---

cypress/integration/recipes_list_spec.js
src/App.test.js
src/pages/Bebidas.jsx
src/pages/Comidas.jsx

Main group 16 req25

---

src/components/CategoriesBar.js
src/components/Header.js
src/context/RecipesProvider.js
src/pages/Drinks.js
src/pages/Meals.js
src/services/cocktailAPI.js
src/services/meailAPI.js

**Tela principal de receitas**

[Grupo 30] - Tela principal de receitas 

---

src/App.js
src/components/ButtonShare.js
src/pages/Explorer.js
src/pages/Profile.js

Implementada página de Perfil
Implementada página Explorer
Criado botão ButtonShare (clipboard)

[Grupo 29] - Perfil, Explorer e ButtonShare

---

src/context/RecipesProvider.js
src/pages/Drinks.js
src/pages/Food.js
src/services/DrinksApiServices.js
src/services/MealApiService.js

tentativa de resolução do requisito 29 (erro na requisição de comidas arquivo MealApiService.js linha 19)

[Grupo7]Main group 7 req28 test

---

package-lock.json
package.json
src/App.js
src/components/DrinksCards.js
src/components/MealsCards.js
src/components/RecommendDrink.js
src/components/RecommendMeal.js
src/components/Searchbar.js
src/pages/DetalhesBebida.js
src/pages/DetalhesComida.js
src/pages/TelaPrincipal.js
src/services/favoriteButton.js
src/services/getItemById.js
src/services/localStorageChecks.js
src/styles/Detalhes.css
src/styles/Recommendations.css

[Grupo 26] Tela de detalhes de (comidas | bebidas)

---

src/components/FiltersCategories.jsx
src/context/RecipesProvider.jsx
src/pages/Drinks.jsx
src/pages/Foods.jsx

…a logica que apenas um filtro pode ser selecionado por vez, requisito 30

[Grupo 14] - Requisitos 29 e 30

---

src/pages/ReceitasFeitas.jsx

[Group 17] -  day4 tela de receitas feitas

---

src/Routes.js
src/pages/ExplorerMealsOrigin.js
src/pages/NotFound.js

**Tela de explorar por local de origem/area**

[Grupo 30] - Tela de explorar por local de origem/area

---

src/App.js
src/components/Cards.js
src/components/Header.js
src/pages/ExploreIngredients.js
src/pages/FavoritedRevenues.js
src/pages/MainPage.js
src/redux/reducers/drinkReducer.js
src/styles/explorerIngredients.css
src/styles/favorite.css
src/styles/header.css

[Grupo 25] - Tela de Explorar Ingredientes

---

src/App.js
src/pages/ExplorarComidasPorArea.jsx
src/pages/NotFound.js

Tela de origem

---

src/App.js
src/hooks/useCurrentRecipe.js
src/pages/BebidaEmProgresso.js
src/pages/ComidaEmProgresso.js
src/pages/DetalhesBebida.js
src/pages/DetalhesComida.js
src/services/getCurrentDate.js
src/services/getIngredients.js
src/services/localStorageChecks.js
src/styles/EmProgresso.css

[Grupo 26] Tela de receitas em progresso

---

src/pages/Profile.jsx
src/styles/pages/profile.css
src/tests/requirementsTests/requirement-82.test.js
src/tests/requirementsTests/requirement-83.test.js
src/tests/requirementsTests/requirement-84.test.js
src/tests/requirementsTests/requirement-85.test.js
src/tests/requirementsTests/requirement-86.test.js
src/tests/requirementsTests/requirement-87.test.js

[Group 15] [Samuel Melo] [Profile Screen]

---

src/pages/Bebidas.jsx
src/pages/Comidas.jsx
src/pages/ExplorarIngredientesBebidas.jsx
src/pages/ExplorarIngredientesComidas.jsx

Reverts tryber/sd-011-project-recipes-app#852

Revert "[Grupo 16] - requisitos 75, 76 e 77"

---

src/App.js
src/components/MenuInferior.js
src/pages/DetalhesBebida.js
src/pages/DetalhesComida.js
src/pages/ExplorarIngredientes.js
src/pages/Profile.js
src/pages/TelaPrincipal.js
src/provider/recipesProvider.js
src/services/requestImage.js
src/services/requestIngredients.js

[Grupo 26] Tela de Explorar Ingredientes

---

src/App.js
src/components/DoneRecipesRender.js
src/components/ReadyRecipeList.js
src/components/RecipeList.js
src/components/RenderCard.js
src/hooks/useCurrentRecipe.js
src/pages/ExplorarArea.js
src/pages/ReadyRecipe.js
src/services/requestAreas.js

[Grupo 26] Tela de Explorar por Área

---

src/Helpers/createDoneRecipes.js
src/Helpers/setDoneRecipes.js
src/Pages/Components/FoodOrDrinkFilter.jsx
src/Pages/Components/InprogressDrink.jsx
src/Pages/Components/InprogressFood.jsx
src/Pages/Components/Secondary/SecondFavoriteButton.jsx
src/Pages/Components/Secondary/SecondShareButton.jsx
src/Pages/FavoriteRecipes.jsx
src/Pages/Foods.jsx
src/Pages/RecipesMade.jsx

[Main-group-33] Tela de Receitas Feitas

---

src/components/FavoriteButton.jsx
src/components/RecipeCard.jsx
src/pages/DrinkDetails.jsx
src/pages/MealDetails.jsx

corrige loop

---

src/pages/Explorer.js
src/pages/ExplorerByArea.js
src/pages/ExplorerDrink.js
src/pages/ExplorerFood.js
src/pages/FavoriteRecipes.js
src/pages/NotFound.js
src/pages/Perfil.js
src/pages/Recipes.js
src/routes/index.js

[Tela de Explorar Por Area] Requisito 78, 79, 80 e 81 resolvidos

---

src/components/FoodsRecomendations.jsx
src/components/subcomponents/ShareAndFavButtons.jsx
src/helpers/ingredientsDrinkDetails.jsx
src/helpers/ingredientsMealDetails.jsx
src/pages/DoneRecipes.jsx
src/pages/DrinksDetails.jsx
src/pages/FoodsDetails.jsx
src/pages/RecipesInProgress.jsx
src/services/API.js

Reverts tryber/sd-011-project-recipes-app#1119

Revert "[GRUPO 14]req 50 test"

---

src/Pages/Perfil.js

Feito a tela, verificar pois houve alguns erros

Implementando a tela de perfil

---

src/components/Clipboard.js
src/components/Clipboard2.js
src/pages/DetailsFood.js

[Melhor que lasanha] Main group 31 clipboard
